/**
 * Apodini-App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Action } from '../model/action';
import { GameResponse } from '../model/gameResponse';
import { GameResponse1 } from '../model/gameResponse1';
import { GameResponse2 } from '../model/gameResponse2';
import { PlayerResponse } from '../model/playerResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DefaultService {

    protected basePath = '';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * GetGame
     * @param gameId @Parameter var gameId: String
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public gETGetGame(gameId: string, observe?: 'body', reportProgress?: boolean): Observable<GameResponse1>;
    public gETGetGame(gameId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GameResponse1>>;
    public gETGetGame(gameId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GameResponse1>>;
    public gETGetGame(gameId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (gameId === null || gameId === undefined) {
            throw new Error('Required parameter gameId was null or undefined when calling gETGetGame.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GameResponse1>('get',`${this.basePath}/v1/game/${encodeURIComponent(String(gameId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * GetGames
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public gETGetGames(observe?: 'body', reportProgress?: boolean): Observable<GameResponse2>;
    public gETGetGames(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GameResponse2>>;
    public gETGetGames(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GameResponse2>>;
    public gETGetGames(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GameResponse2>('get',`${this.basePath}/v1/game`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * CreateGame
     * @param name @Parameter var name: String
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public pOSTCreateGame(name?: string, observe?: 'body', reportProgress?: boolean): Observable<GameResponse1>;
    public pOSTCreateGame(name?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GameResponse1>>;
    public pOSTCreateGame(name?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GameResponse1>>;
    public pOSTCreateGame(name?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (name !== undefined && name !== null) {
            queryParameters = queryParameters.set('name', <any>name);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GameResponse1>('post',`${this.basePath}/v1/game`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * CreatePlayer
     * @param name @Parameter var name: String
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public pOSTCreatePlayer(name?: string, observe?: 'body', reportProgress?: boolean): Observable<PlayerResponse>;
    public pOSTCreatePlayer(name?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PlayerResponse>>;
    public pOSTCreatePlayer(name?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PlayerResponse>>;
    public pOSTCreatePlayer(name?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (name !== undefined && name !== null) {
            queryParameters = queryParameters.set('name', <any>name);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<PlayerResponse>('post',`${this.basePath}/v1/player`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * JoinGame
     * @param gameId @Parameter var gameId: String
     * @param playerId @Parameter var playerId: String
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public pUTJoinGame(gameId: string, playerId?: string, observe?: 'body', reportProgress?: boolean): Observable<GameResponse>;
    public pUTJoinGame(gameId: string, playerId?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GameResponse>>;
    public pUTJoinGame(gameId: string, playerId?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GameResponse>>;
    public pUTJoinGame(gameId: string, playerId?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (gameId === null || gameId === undefined) {
            throw new Error('Required parameter gameId was null or undefined when calling pUTJoinGame.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (playerId !== undefined && playerId !== null) {
            queryParameters = queryParameters.set('playerId', <any>playerId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GameResponse>('put',`${this.basePath}/v1/game/${encodeURIComponent(String(gameId))}/join`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * PassGame
     * @param gameId @Parameter var gameId: String
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public pUTPassGame(gameId: string, observe?: 'body', reportProgress?: boolean): Observable<GameResponse>;
    public pUTPassGame(gameId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GameResponse>>;
    public pUTPassGame(gameId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GameResponse>>;
    public pUTPassGame(gameId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (gameId === null || gameId === undefined) {
            throw new Error('Required parameter gameId was null or undefined when calling pUTPassGame.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GameResponse>('put',`${this.basePath}/v1/game/${encodeURIComponent(String(gameId))}/pass`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * PlayGame
     * @param gameId @Parameter var gameId: String
     * @param body @Parameter var action: Action
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public pUTPlayGame(gameId: string, body?: Action, observe?: 'body', reportProgress?: boolean): Observable<GameResponse>;
    public pUTPlayGame(gameId: string, body?: Action, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GameResponse>>;
    public pUTPlayGame(gameId: string, body?: Action, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GameResponse>>;
    public pUTPlayGame(gameId: string, body?: Action, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (gameId === null || gameId === undefined) {
            throw new Error('Required parameter gameId was null or undefined when calling pUTPlayGame.');
        }


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<GameResponse>('put',`${this.basePath}/v1/game/${encodeURIComponent(String(gameId))}/play`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * StartGame
     * @param gameId @Parameter var gameId: String
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public pUTStartGame(gameId: string, observe?: 'body', reportProgress?: boolean): Observable<GameResponse>;
    public pUTStartGame(gameId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GameResponse>>;
    public pUTStartGame(gameId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GameResponse>>;
    public pUTStartGame(gameId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (gameId === null || gameId === undefined) {
            throw new Error('Required parameter gameId was null or undefined when calling pUTStartGame.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GameResponse>('put',`${this.basePath}/v1/game/${encodeURIComponent(String(gameId))}/start`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
