/**
 * The Game - Endangered Nature Edition, built with Apodini
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { StackofCard } from './stackofCard';

export interface GamePile { 
    id: string;
    stack: StackofCard;
    order: GamePile.OrderEnum;
}
export namespace GamePile {
    export type OrderEnum = 'asc' | 'desc';
    export const OrderEnum = {
        Asc: 'asc' as OrderEnum,
        Desc: 'desc' as OrderEnum
    };
}