/**
 * Apodini-App
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Stack } from './stack';

export interface GamePile { 
    id: string;
    order: GamePile.OrderEnum;
    stack: Stack;
}
export namespace GamePile {
    export type OrderEnum = 'asc' | 'desc';
    export const OrderEnum = {
        Asc: 'asc' as OrderEnum,
        Desc: 'desc' as OrderEnum
    };
}